name: StaffMode
main: nl._xxprodudexx_.staffmode.StaffMode
version: 1.0.1-SNAPSHOT
author: _xXProDudeXx_
description: StaffMode-Plugin

commands:
      staffmode:
              usage: /<command>
              description: Enter or Leave the StaffMode

permissions:
      staffmode.use:
              default: op
      staffmode.admin:
              default: op