name: StaffMode
main: nl._xxprodudexx_.staffmode.StaffMode
version: 1.0.0-SNAPSHOT
author: _xXProDudeXx_
description: StaffMode-Plugin

commands:
      staffmode:

permissions:
      staffmode.use:
              default: op
      staffmode.admin:
              default: op